### ISSUE TITLE
Arch Linux Package

### ISSUE THREAD

**Issue by LefterisJP** [cinemast/libjson-rpc-cpp#89]
I see that you are also the maintainer of the Arch Linux package (AUR) so I am making an issue here.
The latest package does not build due to not being able to find the jsoncpp include directories.

If I clone your master branch it does find it though. The difference lies in `FindJSONCPP.cmake`:

**master**
```
FIND_PATH (JSONCPP_INCLUDE_DIRS json.h
    PATHS
    /usr/include
    /usr/local/include
    ${CMAKE_SOURCE_DIR}/win32-deps/include
    PATH_SUFFIXES jsoncpp/json json
)
```

**AUR package**
```
FIND_PATH(JSONCPP_INCLUDE_DIRS json.h
/usr/include
/usr/local/include
${CMAKE_SOURCE_DIR}/win32-deps/include
PATH_SUFFIXES jsoncpp/json jsoncpp
)
```

There is no include directory called `jsoncpp` anymore. It's simply json, hence why the `master` branch version works.
Please update the AUR package so that at least the FindJSONJCPP.cmake is correct.

**Comment by cinemast** [comment]
This should already have been fixed in 0.4.2-1 on AUR. I just did a full rebuild of the package. I cannot reproduce the error.

Also the FindJSONCPP.cmake looks fine. I quote from the v0.4.2 tarball which is used in the AUR package:

```
# - Try to find JSONCPP
# Once done this will define
#
#  JSONCPP_FOUND - system has JSONCPP
#  JSONCPP_INCLUDE_DIRS - the JSONCPP include directory
#  JSONCPP_LIBRARY - Link these to use JSONCPP

FIND_LIBRARY (JSONCPP_LIBRARIES NAMES jsoncpp
    PATHS
    /usr/lib
    /usr/local/lib
    ${CMAKE_SOURCE_DIR}/win32-deps/lib
)

FIND_PATH (JSONCPP_INCLUDE_DIRS json.h
    PATHS
    /usr/include
    /usr/local/include
    ${CMAKE_SOURCE_DIR}/win32-deps/include
    PATH_SUFFIXES jsoncpp/json json
)

IF(JSONCPP_INCLUDE_DIRS AND JSONCPP_LIBRARIES)
    SET(JSONCPP_FOUND TRUE)
ENDIF(JSONCPP_INCLUDE_DIRS AND JSONCPP_LIBRARIES)

IF(JSONCPP_FOUND)
    if(EXISTS "${JSONCPP_INCLUDE_DIRS}/version.h")
        MESSAGE(STATUS "Found New libjsoncpp: ${JSONCPP_LIBRARIES}")
        set(JSONCPP_INCLUDE_PREFIX "json")
    else()
        MESSAGE(STATUS "Found old libjsoncpp: ${JSONCPP_LIBRARIES}")
        set(JSONCPP_INCLUDE_PREFIX "jsoncpp/json")
    endif()
ELSE(JSONCPP_FOUND)
    IF(JSONCPP_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find libjsoncpp")
    ENDIF(JSONCPP_FIND_REQUIRED)
ENDIF(JSONCPP_FOUND)

MARK_AS_ADVANCED(
    JSONCPP_LIBRARIES
    JSONCPP_INCLUDE_DIRS
)
```

The PATH_SUFFIXES should take care of this. Please double check if you have the latest PKGBUILD from the AUR.

**Comment by LefterisJP** [comment]
All right so I think I provided some misinformation a bit. All that I reported above is from: [libjson-rpc-cpp-git](https://aur.archlinux.org/packages/libjson-rpc-cpp-git/)

The normal package [libjson-rpc-cpp](https://aur.archlinux.org/packages/libjson-rpc-cpp/) still does not build but for some other reason. Namely when the build ends and the unit tests start I get this:

```
Linking CXX executable ../../bin/unit_testsuite
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
src/test/CMakeFiles/unit_testsuite.dir/build.make:369: recipe for target 'bin/unit_testsuite' failed
make[2]: *** [bin/unit_testsuite] Error 1
CMakeFiles/Makefile2:675: recipe for target 'src/test/CMakeFiles/unit_testsuite.dir/all' failed
make[1]: *** [src/test/CMakeFiles/unit_testsuite.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
```

I don't get this if I simply clone the repository's master branch, build and install myself.

**Comment by cinemast** [comment]
How are you trying to build the package? There is a patch on AUR along the pkgbuild that should fix that problem.

**Comment by cinemast** [comment]
Commando back. I downloaded a fresh version of it. I see the problem now.

**Comment by cinemast** [comment]
Just uploaded a new version of it to AUR: 
https://aur.archlinux.org/packages/libjson-rpc-cpp/

Do you know who created the second aur? I think it is confusing if there are 2 versions of it.

**Comment by LefterisJP** [comment]
Thank you, with the new AUR version it seems to work. No I am not aware of who made the other package but I can imagine the reason looking at what the package is required from.

It seems to be a package meant to work with [cpp-ethereum](https://github.com/ethereum/cpp-ethereum). I am a member of that project and since so far and especially in Ubuntu we were using an older version of jsoncpp we were using a specific commit from json-rpc-cpp too. A mess truly.

We are in the process of trying to make our dependency on both jsoncpp and jsonrpc-cpp be more clear and flexible. Once that's done I guess there will be no reason for that other package to exist.
